/*
  Copyright (C) 2011, Claudio Lucchese

  This file is part of DMT.

  DMT is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  DMT is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with DMT. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __DMT_DATA_CONVERSION_H
#define __DMT_DATA_CONVERSION_H

#include "../inc/basicstruct.hh"  // IO Exceptions

/**
 * Converts from DMT_Weighted_Transaction to DMT_Transaction.
 * It may also output the class labels
 *
 * \param input_file input file containing weighted transactions
 * \param output_file output file that will contain the plain transactions
 */
void DMT_wt2t(char* input_file, char* output_file);

/**
 * Converts from DMT_Labeled_Weighted_Transaction to DMT_Weighted_Transaction.
 * It may also output the class labels
 *
 * \param input_file input file containing labels weighted transactions
 * \param output_file output file that will contain the weighted transactions
 * \param classes_file the file that will contain class labels only.
 * 			If NULL this file is not generated.
 */
void DMT_lwt2wt(char* input_file, char* output_file, char* classes_file=0);

/**
 * Converts from DMT_Labeled_Weighted_Transaction to DMT_Transaction.
 * It may also output the class labels
 *
 * \param input_file input file containing labels weighted transactions
 * \param output_file output file that will contain the transactions
 * \param classes_file the file that will contain class labels only.
 * 			If NULL this file is not generated.
 */
void DMT_lwt2t(char* input_file, char* output_file, char* classes_file=0);

/**
 * Counts the number of classes of a dataset in DMT_Labeled_Weighted_Transaction format
 *
 * \param input_file input file containing labels weighted transactions
 * \return the number of classes
 */
int DMT_lwt_countLabels(char* input_file);

/**
 * Converts from DMT_Transaction to DMT_Lebeled_Transaction.
 * by adding a fake label 0
 *
 * \param input_file input file containing  transactions
 * \param output_file output file that will contain the labeled transactions
 */
void DMT_t2lt(char* input_file, char* output_file);

/**
 * Converts from DMT_Lebeled_Transaction to DMT_Labeled_Weighted_Transaction.
 * by adding a fake weight 1.0
 *
 * \param input_file input file containing labeled transactions
 * \param output_file output file that will contain the weighted labeled transactions
 */
void DMT_lt2lwt(char* input_file, char* output_file);


/*  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *        ASSO Format Conversion
 *  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

/**
 * Converts from DMT_Transaction to the DBP sparse format.
 *
 * \param input_file input file containing  transactions
 * \param output_file output file that will contain the labeled transactions
 */
void DMT_t2sparsedbp(char* input_file, char* output_file);

/**
 * Converts from DBP output format to DMT_ExtSuppSet.
 *
 * \param item_file input file containing ASSO items
 * \param tran_file input file containing ASSO transactions
 * \param output_file output file that will contain patterns in DMT_ExtSuppSet format
 * \return the number of patterns found, which depend also on 0-rows generated by asso
 */
int DMT_dbp2extsuppset(char* item_file, char* tran_file, char* output_file) throw (DMT_Error*);


void DMT_checklenghts(char* a, char* b);

#endif
